### ISSUE TITLE
I2C1 with non-default PADs setup does not work until command line

### ISSUE THREAD

**Issue by fernandez85** [karo-electronics/karo-tx-uboot#5]
Hello community :)

I have a really big problem with I2C. I'm developing a product which uses Karo _**TX6S-8135**_ chip and using latest sources that are placed here on Github (_**master**_ branch - to be precise, this is my dev starting point [CLICK](https://github.com/karo-electronics/karo-tx-uboot/tree/03e74e4d42ff4a67a607eb7f687d66bbbb6914ef) ). I have request to do a U-Boot modification. I need to detect at U-Boot init time if button was pressed (it's non-stadard keypad), which is controlled by I2C1. The problem here is our product uses different pins (_CSI0_DAT9_, _CSI0_DAT8_) than default ones (_EIM_D21_, _EIM_D28_). The defaults are used for internal I2C to control PMIC, but chip specification shows that I2C1 module can work with pin numbers 161 and 162, which are mentioned _CSI0_DAT8_ and _CSI0_DAT9_ pins. This is also mentioned here in Karo datasheet:
[TX6S-Datasheet.pdf](https://www.karo-electronics.de/fileadmin/download/Datasheets/TX6S-Datasheet.pdf) (pages 11-12)

First I wanted to check if I have any connection with the slave module that controls my keypad  (TCA9539 in my case). Here is what happens. When I2C Probe is executed while initializing it fails - currently i use **_board_late_init_**, but goal is to do it earlier. When I execute `i2c probe` after initialization, at U-Boot command line state, then it's OK and whole communication is working correctly. I tried different approaches, but nothing helps here. All this situation can be seen in this logfile:
[tx6s_log.txt](https://github.com/karo-electronics/karo-tx-uboot/files/3082272/tx6s_log.txt)

Here are necessary changes (trimmed to minimum) to reproduce problem:
[git_diff.txt](https://github.com/karo-electronics/karo-tx-uboot/files/3082260/git_diff.txt)

Unfortunately, I don't have any circuit diagram of the device. It was supposed to be easy change, and all necessary info was provided to achieve this. Now I'm stuck at this point and can't go through. I don;t understand why _i2c probe_  works from console and not while initializing. I can also add that `reset` command (CPU reset) makes that my code works as expected, but that is just a different state.
I appreciate any help with this topic as I'm out of ideas now :(

**Comment by hsdenx** [comment]
Hello fernandez85,

very strange ... no real idea, without the posibility to dig on the hardware.
May its time to use an oscilloscope...

Hmm.. may you try to set the pins EIM_D21, EIM_D28 to gpio function?

bye,
Heiko

**Comment by fernandez85** [comment]
Hello,

yes very strange, and I'm struggling with this for a long time.
Already tried to set GPIO mode to EIM_D21 and EIM_D28 - no success :(
As for the oscilloscope , I don't have such device on my side, but I asked a developer who is responsible for this project and he did a bunch of measurements for me.
All these where done on SDA line of the I2C module.
This was done when slave module wasn't connected.
![image](https://user-images.githubusercontent.com/8377386/56194619-a89d7200-6033-11e9-932c-8d550a84e4e8.png)
From what I was informed same measurement was achieved while U-Boot init and while in U-Boot command-line.
Situation is little different when slave controller is connected to SDA,SCL lines. 
This is from U-Boot init time:
![image](https://user-images.githubusercontent.com/8377386/56196021-56118500-6036-11e9-8372-bdff559f8e69.png)
And this from U-Boot command-line:
![image](https://user-images.githubusercontent.com/8377386/56196092-780b0780-6036-11e9-8b53-9772947e8204.png)
This doesn't say anything to me, as I'm not a specialist in this area. I'm only seeing that the graph is different a little. But I don't know if this fits measurement error margin or if not what does it mean?

Kind regards,
Piotr K (fernandez85)

**Comment by fernandez85** [comment]
Hello,
With help of guys from KaRo support crew I've found he solution here. 
Long story short. All I needed is to set up PAD for Reset-Pin of the controller that I wanted to use.
The reason why it worked in command-line was that this pin was actually set when PADs for Starterkit Eval board were setup, but at that moment I didn't know that one of those PADs was my Reset-Pin ;)
So the problem is solved here.
Cheers,
Piotr K (fernandez85)
