### ISSUE TITLE
U-boot SPL fails to clear global data on TX25

### ISSUE THREAD

**Issue by SuperDeathMonkey** [karo-electronics/karo-tx-uboot#6]
Built u-boot for Karo TX25 module from [KARO-TX25-2017-08-17](https://github.com/karo-electronics/karo-tx-uboot/releases/tag/KARO-TX25-2017-08-17) release.
Flashed SPL image to NAND, attached BDI3000 debugger, see a SIGABRT is raised at /arch/arm/crt0.S line 96. Looks like it's failing to zero the global data which is being allocated at the top of SRAM (128 Kbyte internal RAM of IMX25 0x78000000 - 0x78020000).
Moving the global data store to SDRAM (bank 0) still get the same issue trying to zero the memory.
The only workaround I could find was removing the zeroing of global data from crt0.S and adding 
```C
memset((void *)gd, '\0', sizeof(gd_t));
``` 
to the board_init_f function in tx25.c.

Slightly baffled as to why I am unable to write to SRAM or SDRAM when in crt0.S but works fine from board_init_f.

**Comment by loethi** [comment]
We do not maintain or support U-Boot on TX25. Please refer to board/karo/tx25/MAINTAINERS for the appropriate contact.
